import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Script from 'next/script'
import { useContext, useEffect, useState } from 'react'
import { Container, Nav, Navbar } from 'react-bootstrap';
import AuthContext from '@/pages/context/AuthContext'
import stl from '@/styles/Customstyle.module.css'
const inter = Inter({ subsets: ['latin'] })
import logo from '../../public/BusLogo.png'


export async function getStaticProps(context) {
  let data = await fetch(`http://127.0.0.1:8000/searchbus/`);
  let res = await data.json()
  console.log(res[0]);
  return {
    props: { res },
  }
}

export default function Navbar1() {
  const { user, logoutUser } = useContext(AuthContext)
  const [admin, setAdmin] = useState(false)
  useEffect(() => {
    getUserType();
  }, [user])

  const getUserType = async (e) => {
    let res = await fetch(`http://127.0.0.1:8000/usertype/${user ? user.username : "no"}`)
    let usertype = await res.json()
    console.log("USER TYPE=", user, usertype.type)
    if (usertype.type == "Admin")
      setAdmin(true)
    else
      setAdmin(false)

  }
  return (
    <>
      {/* <Head>
        <title>Dream Bus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"></link>
      </Head> */}
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" ></Script>
      <div className="position-fixed w-100 z-2 ">

        {user ? admin ?
          <nav className="navbar">
            <div className="logo ms-3"><Image src={logo} className="w-100" style={{ height: "100%" }} /></div>
            <ul className="nav-links me-3">
              <input type="checkbox" id="checkbox_toggle" />
              <label for="checkbox_toggle" className="hamburger">&#9776;</label>
              <div className="menu">
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/adminhome">Home</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/ownerprofile">Profile</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/buslist">Buses</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/busbooking">Bookings</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/login" onClick={logoutUser}>Logout</Link></li>
              </div>
            </ul>
          </nav>
          :
          <nav className="navbar">
            <div className="logo ms-3"><Image src={logo} className="w-100" style={{ height: "100%" }} /></div>
            <ul className="nav-links me-3">
              <input type="checkbox" id="checkbox_toggle" />
              <label for="checkbox_toggle" className="hamburger">&#9776;</label>
              <div className="menu">
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/userhome">Home</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/searchbus">Search</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/bookinghistory">Bookings</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/userprofile">Profile</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/busdb/about">About Us</Link></li>
                <li className={`${stl.navbarlistitems}`}><Link href="/login" onClick={logoutUser}>Logout</Link></li>
              </div>
            </ul>
          </nav>
          :
          <>
            <nav className="navbar" style={{ backgroundColor: "transparent", height: "4rem" }}>
              <div className="logo mx-auto pulse"><Image src={logo} className="w-100" style={{ height: "100%" }} /></div>
            </nav></>
        }

      </div>
    </>
  )
}
