import '@/styles/globals.css'
import Navbar from '../src/components/navbar'
import { AuthProvider } from '../pages/context/AuthContext'
import { useState } from 'react'
import Head from 'next/head'
import Script from 'next/script'
import 'bootstrap/dist/css/bootstrap.min.css';



export default function MyApp({ Component, pageProps }) {
  return (<>
    <Head>
      <title>Dream Bus</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/BusLogo.png" />
    </Head>
    
    <AuthProvider>
      <Navbar />
      <Component {...pageProps} />

    </AuthProvider>
  </>
  )

}