# Generated by Django 4.1.7 on 2023-04-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.CharField(max_length=122)),
                ('busname', models.CharField(default='', max_length=122)),
                ('seat', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('SE', 'Seater'), ('SL', 'Sleeper'), ('SS', 'Semisleeper')], default='SE', max_length=20)),
                ('frontimg', models.ImageField(default='', upload_to='busImages')),
                ('sideimg', models.ImageField(default='', upload_to='busImages')),
                ('interiorimg', models.ImageField(default='', upload_to='busImages')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('address', models.CharField(default='', max_length=122)),
                ('dob', models.DateField()),
                ('phone', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(default='', max_length=122)),
                ('dest', models.CharField(default='', max_length=122)),
                ('via', models.CharField(default='', max_length=122)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='app.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
            ],
        ),
        migrations.CreateModel(
            name='Owns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus')),
                ('oid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operator')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus', to='app.operator'),
        ),
    ]
