# Generated by Django 4.1.7 on 2023-04-03 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('dep', models.CharField(default='', max_length=122)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course', to='app.instructor')),
                ('veh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veh', to='app.vehicles')),
            ],
        ),
    ]
