# Generated by Django 4.1.7 on 2023-04-03 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=122)),
                ('dob', models.DateField()),
                ('address', models.CharField(default='', max_length=122)),
                ('experience', models.CharField(default='', max_length=122)),
                ('phone', models.CharField(default='', max_length=122)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='app.bus')),
            ],
        ),
    ]
