# Generated by Django 4.1.7 on 2023-04-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='reachtime',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AddField(
            model_name='route',
            name='starttime',
            field=models.CharField(default='', max_length=122),
        ),
    ]
