# Generated by Django 4.1.7 on 2023-04-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_person_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='seatno',
            field=models.IntegerField(default=10),
        ),
    ]
