# Generated by Django 4.1.7 on 2023-04-05 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_seatno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seatno',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat1', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat2', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat3', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat4', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat5', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat6', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat7', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat8', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat9', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat10', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat11', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat12', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat13', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat14', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat15', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat16', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat17', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat18', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat19', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat20', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat21', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat22', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat23', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat24', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat25', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat26', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat27', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat28', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat29', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat30', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat31', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('seat32', models.CharField(choices=[('B', 'Booked'), ('A', 'Availabe')], default='A', max_length=20)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='app.bus')),
            ],
        ),
    ]
