# Generated by Django 4.1.7 on 2023-04-08 09:33

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_booking_seatno_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=app.models.upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='bus',
            name='frontimg',
            field=models.ImageField(default='busImages\\BusLogo.jpg', upload_to='busImages'),
        ),
    ]
