# Generated by Django 4.1.7 on 2023-04-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_seat1_seat_seat_remove_seat_seat10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='setno',
            field=models.IntegerField(default=0),
        ),
    ]
