# Generated by Django 4.1.7 on 2023-04-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rename_setno_seat_seatno'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
