# Generated by Django 4.1.7 on 2023-04-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_seat_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
