# Generated by Django 4.1.7 on 2023-04-21 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_booking_user_delete_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
