# Generated by Django 4.1.7 on 2023-04-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_person_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
