# Generated by Django 4.1.7 on 2023-04-22 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('ticketno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('bookingdate', models.DateTimeField(auto_now_add=True)),
                ('seatno', models.IntegerField()),
                ('amt', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app.bus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='app.person')),
            ],
        ),
    ]
