# Generated by Django 4.1.7 on 2023-07-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_person_img_alter_operator_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(default='busImages/adminlogo.png', upload_to='busImages'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
        migrations.DeleteModel(
            name='Vehicles',
        ),
    ]
