# Generated by Django 4.1.7 on 2023-07-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_delete_book_alter_person_img_delete_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='reachtime',
            field=models.DateTimeField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='route',
            name='starttime',
            field=models.DateTimeField(default='', max_length=122),
        ),
    ]
